import Footer from "@components/layouts/Footer";
import ContactForm from "@components/shared/ContactForm";
import FloatingImages from "@components/shared/FloatingImages";
import Header from "@components/shared/Header";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

const Contacts: NextPage = () => {
  const router = useRouter();
  const [serviceId, setServiceId] = useState(0);
  useEffect(() => {
    if (router.query.service) {
      setServiceId(parseInt(router.query.service as string));
    }
  }, [router.query]);

  return (
    <div>
      <Head>
        <title>Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header title="Contacts" />
        <div className="relative grid grid-cols-1 md:mx-20 md:grid-cols-2">
          <FloatingImages />
          <ContactForm selectedService={serviceId} />
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Contacts;
