import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../common/components/layouts/Navbar";
import HomeSvg from "../common/assets/svg/homebg.svg";
import WaveSvg from "../common/assets/svg/wave.svg";

const Contacts: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-primary-500 relative">
        <Navbar />
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 px-2 sm:mt-10">
      <h1 className="text-5xl font-bold text-bleu ">Contactez Nous</h1>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 px-2 sm:mt-10">
        <div>
          <h2>Tel:6654512450</h2>
          <h2>Email:info@wdsagency.com</h2>
          <h2>Localisation: Dschang,Cameroun</h2>
        </div>

        <div>
          <form>
            <p>
              <label>Name</label>
              <input type="text" name="user_name" />
            </p>
            <p>
              <label>Email</label>
              <input type="email" name="user_email" />
            </p>
            <p>
              <label>Message</label>
              <textarea name="message" />
            </p>
            <p>
              <input type="submit" value="Send" />
            </p>
          </form>
        </div>
      </div>
    </div>
  );
};

export default Contacts;
