import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../common/components/layouts/Navbar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="container px-4 mx-auto">
        <h1 className="mb-4 text-3xl font-bold text-center">wds agency</h1>
      </div>
    </div>
  );
};

export default Home;
